# Generated by Django 2.0.3 on 2019-05-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190515_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='currentPercent',
            field=models.FloatField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='twelfthPercent',
            field=models.FloatField(max_length=5, null=True),
        ),
    ]
