# Generated by Django 2.0.3 on 2019-05-17 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190515_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('userDetails', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('about', models.CharField(max_length=200)),
                ('highestQualification', models.CharField(max_length=50)),
                ('tenthPercent', models.FloatField(max_length=5, null=True)),
                ('twelfthPercent', models.FloatField(max_length=5, null=True)),
                ('currentPercent', models.FloatField(max_length=5, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='currentPercent',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='highestQualification',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='tenthPercent',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='twelfthPercent',
        ),
    ]
