# Generated by Django 2.0.3 on 2019-05-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190517_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
