# Generated by Django 2.0.3 on 2019-05-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_details_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='userDetails',
        ),
        migrations.AddField(
            model_name='details',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='details',
            name='about',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='details',
            name='highestQualification',
            field=models.CharField(default='', max_length=50),
        ),
    ]
