# Generated by Django 2.0.3 on 2019-05-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190517_1657'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Details',
        ),
        migrations.AddField(
            model_name='customuser',
            name='about',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='currentPercent',
            field=models.FloatField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='highestQualification',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tenthPercent',
            field=models.FloatField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='twelfthPercent',
            field=models.FloatField(max_length=5, null=True),
        ),
    ]
