# Generated by Django 2.0.3 on 2019-05-18 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190517_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(default='', max_length=200)),
                ('highestQualification', models.CharField(default='', max_length=50)),
                ('tenthPercent', models.FloatField(max_length=5, null=True)),
                ('twelfthPercent', models.FloatField(max_length=5, null=True)),
                ('currentPercent', models.FloatField(max_length=5, null=True)),
                ('category', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='about',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='category',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='currentPercent',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='highestQualification',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='tenthPercent',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='twelfthPercent',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
