# Generated by Django 2.0.3 on 2019-05-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190518_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='flag',
            field=models.CharField(default='first', max_length=5),
        ),
    ]
