# Generated by Django 2.0.3 on 2019-05-21 09:13

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tenthPercent',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twelfthPercent',
        ),
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Internships', 'Internships'), ('Scholarships', 'Scholarships'), ('Entrance exams', 'Entrance exams'), ('Jobs', 'Jobs'), ('Events', 'Events'), ('Higher education', 'Higher education'), ('Startups', 'Startups'), ('Fellowships', 'Fellowships'), ('Data Science', 'Data Science'), ('Artificial Intelligence', 'Artificial Intelligence')], default='none', max_length=126),
        ),
    ]
