# Generated by Django 2.0.3 on 2019-05-21 09:52

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190521_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Internships', 'Internships'), ('Scholarships', 'Scholarships'), ('EntranceExams', 'EntranceExams'), ('Jobs', 'Jobs'), ('Events', 'Events'), ('HigherEducation', 'HigherEducation'), ('Startups', 'Startups'), ('Fellowships', 'Fellowships'), ('DataScience', 'DataScience'), ('ArtificialIntelligence', 'ArtificialIntelligence')], default='none', max_length=122),
        ),
    ]
