# Generated by Django 2.0.3 on 2019-05-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20190521_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'invalid': 'Username should be atleast 6 characters long'}, max_length=30, unique=True),
        ),
    ]
