# Generated by Django 2.0.3 on 2019-05-22 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190521_2037'),
        ('users', '0012_auto_20190521_1409'),
    ]

    operations = [
    ]
